"""empty message

Revision ID: 7177e1c2e14c
Revises: d2bb96fb074b
Create Date: 2017-08-21 13:59:28.361000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7177e1c2e14c'
down_revision = 'd2bb96fb074b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('addziduan11', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'addziduan11')
    # ### end Alembic commands ###
